version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe-nextjs
    ports:
      - '3000:3000'
    volumes:
      - .:/user/src/
      - /user/src/node_modules